kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-storageclass
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard
  replication-type: regional-pd
allowedTopologies:
  - matchLabelExpressions:
      - key: failure-domain.beta.kubernetes.io/zone
        values:
          - us-central1-c
          - us-central1-b
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
spec:
  storageClassName: jenkins-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
