package com.xintongthecoder.accountingbook.entity;

public enum Category {

    ALL, GROCERY, RESTAURANT, HOUSEHOLD, HOUSING, TAX, UTILITY, TRANSPORTATION, CLOTHING, HEALTHCARE, PERSONALCARE, LEARNING, SPORT, HOBBY, ENTERTAINMENT, TRAVEL, SOCIAL, MEMBERSHIP, MISCELLANEOUS;
}
